"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Send } from "lucide-react";
import { withEstablishmentQuery } from "@/lib/school/establishmentContext";
import { SchoolAdminButton } from "@/components/school-admin/ui/Button";
import { SchoolAdminFormField, SchoolAdminInput, SchoolAdminSelect, SchoolAdminTextarea } from "@/components/school-admin/ui/FormControls";
import { SchoolAdminAlert } from "@/components/school-admin/ui/Feedback";

export function FormulaireMessage({ departements, establishmentId }: { departements: string[]; establishmentId: string }) {
  const router = useRouter(); const [isPending, startTransition] = useTransition(); const [canal, setCanal] = useState<"global" | "departement">("global"); const [departement, setDepartement] = useState(departements[0] ?? ""); const [titre, setTitre] = useState(""); const [contenu, setContenu] = useState(""); const [error, setError] = useState<string | null>(null);
  async function handleSubmit(event: React.FormEvent) { event.preventDefault(); if (isPending) return; setError(null); startTransition(async () => { try { const res = await fetch("/api/messagerie/envoyer", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ titre, contenu, canal, departement_disciplinaire: canal === "departement" ? departement : undefined, requestedEstablishmentId: establishmentId }) }); const data = await res.json(); if (!res.ok) { setError(data.error ?? "Erreur inattendue"); return; } setTitre(""); setContenu(""); router.push(withEstablishmentQuery("/pro/messagerie?sent=1", establishmentId)); router.refresh(); } catch { setError("Impossible d’envoyer le message pour le moment."); } }); }
  return <form onSubmit={handleSubmit} className="space-y-5">{error && <SchoolAdminAlert tone="danger">{error}</SchoolAdminAlert>}<fieldset><legend className="mb-2 text-sm font-semibold">Destinataire</legend><div className="grid gap-2 sm:grid-cols-2">{(["global", "departement"] as const).map((value) => <button key={value} type="button" onClick={() => setCanal(value)} aria-pressed={canal === value} className={`min-h-11 rounded-lg border px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--school-admin-focus)] ${canal === value ? "border-[var(--school-admin-primary)] bg-[var(--school-admin-primary-soft)]" : "border-[var(--school-admin-border)]"}`}>{value === "global" ? "Tout l’établissement" : "Département disciplinaire"}</button>)}</div></fieldset>{canal === "departement" && (departements.length ? <SchoolAdminFormField id="message-department" label="Département" required><SchoolAdminSelect value={departement} onChange={(event) => setDepartement(event.target.value)}>{departements.map((item) => <option key={item}>{item}</option>)}</SchoolAdminSelect></SchoolAdminFormField> : <SchoolAdminAlert tone="warning">Aucun département disciplinaire n’est disponible.</SchoolAdminAlert>)}<SchoolAdminFormField id="message-title" label="Titre" required><SchoolAdminInput value={titre} onChange={(event) => setTitre(event.target.value)} maxLength={200} /></SchoolAdminFormField><SchoolAdminFormField id="message-content" label="Contenu" description={`${contenu.length}/4000 caractères`} required><SchoolAdminTextarea value={contenu} onChange={(event) => setContenu(event.target.value)} maxLength={4000} rows={5} /></SchoolAdminFormField><div className="flex justify-end"><SchoolAdminButton type="submit" loading={isPending} disabled={canal === "departement" && !departements.length} leadingIcon={<Send size={16} aria-hidden="true" />}>Envoyer le message</SchoolAdminButton></div></form>;
}
