"use client";
import { useState } from "react";
import { supabase } from "@/lib/supabase";
import { SchoolAdminSectionCard } from "@/components/school-admin/ui/Card";
import { SchoolAdminButton } from "@/components/school-admin/ui/Button";
import { SchoolAdminFormField, SchoolAdminInput, SchoolAdminSelect } from "@/components/school-admin/ui/FormControls";
import { SchoolAdminAlert } from "@/components/school-admin/ui/Feedback";

type Config = { devise: string; frequence_paie: string; seuil_retard_minutes: number; taux_heure_sup_multiplicateur: number; jour_paie: number | null } | null;
export function FormulaireConfigurationPaie({ etablissementId, initial }: { etablissementId: string; initial: Config }) {
  const [form, setForm] = useState({ devise: initial?.devise ?? "FCFA", frequence_paie: initial?.frequence_paie ?? "mensuelle", seuil_retard_minutes: initial?.seuil_retard_minutes ?? 10, taux_heure_sup_multiplicateur: initial?.taux_heure_sup_multiplicateur ?? 1.25, jour_paie: initial?.jour_paie ?? 28 }); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (saving) return; setSaving(true); setSaved(false); setError(""); const { error: saveError } = await supabase.from("payroll_config").upsert({ etablissement_id: etablissementId, ...form, updated_at: new Date().toISOString() }); setSaving(false); if (saveError) { setError(saveError.message); return; } setSaved(true); setTimeout(() => setSaved(false), 3000); }
  return <form onSubmit={save} className="space-y-6">{error && <SchoolAdminAlert tone="danger">{error}</SchoolAdminAlert>}{saved && <SchoolAdminAlert tone="success">Configuration enregistrée.</SchoolAdminAlert>}<SchoolAdminSectionCard title="Cadre de paie" description="Devise, fréquence et jour de versement utilisés par la configuration actuelle."><div className="grid gap-4 sm:grid-cols-2"><SchoolAdminFormField id="payroll-currency" label="Devise"><SchoolAdminInput value={form.devise} onChange={(event) => setForm({ ...form, devise: event.target.value })} /></SchoolAdminFormField><SchoolAdminFormField id="payroll-frequency" label="Fréquence de paie"><SchoolAdminSelect value={form.frequence_paie} onChange={(event) => setForm({ ...form, frequence_paie: event.target.value })}><option value="mensuelle">Mensuelle</option><option value="quinzaine">Quinzaine</option><option value="hebdomadaire">Hebdomadaire</option></SchoolAdminSelect></SchoolAdminFormField><SchoolAdminFormField id="payroll-day" label="Jour de paie" description="Valeur comprise entre 1 et 28."><SchoolAdminInput type="number" min={1} max={28} value={form.jour_paie ?? ""} onChange={(event) => setForm({ ...form, jour_paie: event.target.value ? Number(event.target.value) : null })} /></SchoolAdminFormField></div></SchoolAdminSectionCard><SchoolAdminSectionCard title="Règles horaires" description="Les unités et valeurs restent celles du moteur existant."><div className="grid gap-4 sm:grid-cols-2"><SchoolAdminFormField id="payroll-lateness" label="Seuil de retard" description="En minutes."><SchoolAdminInput type="number" value={form.seuil_retard_minutes} onChange={(event) => setForm({ ...form, seuil_retard_minutes: Number(event.target.value) })} /></SchoolAdminFormField><SchoolAdminFormField id="payroll-overtime" label="Multiplicateur des heures supplémentaires"><SchoolAdminInput type="number" step="0.05" value={form.taux_heure_sup_multiplicateur} onChange={(event) => setForm({ ...form, taux_heure_sup_multiplicateur: Number(event.target.value) })} /></SchoolAdminFormField></div></SchoolAdminSectionCard><div className="flex justify-end"><SchoolAdminButton type="submit" loading={saving}>Enregistrer la configuration</SchoolAdminButton></div></form>;
}
