"use client";

import Image from "next/image";
import Link from "next/link";
import { BookOpen, Building2, Camera, CheckCircle2, GraduationCap, Heart, Mail, MapPin, MessageCircle, Phone, ShieldCheck, Trophy, UsersRound } from "lucide-react";
import type { MiniSiteRendererData } from "@/lib/schoolPage/miniSiteData";
import { buildMiniSiteViewHref } from "@/lib/schoolPage/miniSiteViews";

const gallery = ["guyskull-facade-v1.png", "guyskull-classroom-v1.png", "guyskull-school-life-concept-v1.png", "guyskull-computer-room-concept-v1.png", "guyskull-play-sport-concept-v1.png", "guyskull-library-concept-v1.png"];
const levels = [
  { title: "Maternelle", detail: "Petite, Moyenne, Grande Section", age: "3 – 5 ans", tone: "bg-emerald-50 text-emerald-700" },
  { title: "Primaire", detail: "CI · CP · CE1 · CE2 · CM1 · CM2", age: "6 – 11 ans", tone: "bg-blue-50 text-blue-700" },
  { title: "Secondaire 1er cycle", detail: "6e · 5e · 4e · 3e", age: "11 – 15 ans", tone: "bg-violet-50 text-violet-700" },
  { title: "Secondaire 2nd cycle", detail: "Seconde · Première · Terminale", age: "15 – 18 ans", tone: "bg-orange-50 text-orange-700" },
];

export function GuyskullShowcase({ data, baseHref }: { data: MiniSiteRendererData; baseHref: string }) {
  const school = data.establishment;
  const phone = school.phone;
  const whatsapp = school.whatsapp;
  const location = [school.neighborhood, school.city].filter(Boolean).join(", ") || "Douala, Cameroun";
  const nav = [
    ["Accueil", "accueil"], ["À propos", "etablissement"], ["Programmes", "admissions"], ["Frais de scolarité", "admissions"], ["Vie scolaire", "vie"], ["Résultats", "vie"], ["Galerie", "galerie"], ["Actualités", "vie"], ["Contact", "galerie"],
  ] as const;
  return <div className="bg-[#f8fafc] text-[#102750]">
    <section className="relative min-h-[390px] overflow-hidden">
      <Image src="/images/guyskull/guyskull-campus-master-v1.png" alt="Campus GuySkull" fill priority sizes="100vw" className="object-cover" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#052d64]/90 via-[#07539b]/70 to-[#06366b]/20" />
      <div className="relative mx-auto flex min-h-[390px] max-w-[1440px] items-end gap-8 px-5 pb-8 pt-24 lg:px-8">
        <div className="hidden h-52 w-52 shrink-0 place-items-center rounded-[34px] border-4 border-white bg-white shadow-2xl md:grid">
          <div className="grid h-36 w-36 place-items-center rounded-full border-[10px] border-[#0c3971] text-center"><span className="text-5xl font-black text-[#0c3971]">GS</span><span className="-mt-6 text-[10px] font-black uppercase tracking-widest text-[#0c3971]">International School</span></div>
        </div>
        <div className="min-w-0 flex-1 text-white"><h1 className="text-4xl font-black tracking-tight md:text-5xl">GuySkull International School</h1><p className="mt-2 text-lg">Discipline • Excellence • Ouverture sur le monde</p>
          <div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">Établissement privé</span><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">Bilingue (Français - Anglais)</span><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">Primaire</span><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">Secondaire</span></div>
          <div className="mt-5 flex flex-wrap items-center gap-4 text-sm font-semibold"><span className="inline-flex items-center gap-2"><MapPin size={17}/>{location}</span><span className="inline-flex items-center gap-2 rounded-lg bg-emerald-100 px-3 py-2 text-emerald-700"><CheckCircle2 size={17}/>Établissement vérifié</span></div>
        </div>
        <div className="absolute right-5 top-5 flex gap-3"><button className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#102750] shadow"><Heart size={17} className="mr-2 inline"/>Ajouter aux favoris</button></div>
      </div>
    </section>
    <nav aria-label="Sections de l’établissement" className="sticky top-[72px] z-30 overflow-x-auto border-b border-slate-200 bg-white shadow-sm"><div className="mx-auto flex min-w-max max-w-[1440px] px-4">{nav.map(([label,key], i)=><Link key={`${label}-${i}`} href={buildMiniSiteViewHref(baseHref,key)} className={`flex h-14 items-center gap-2 border-b-2 px-4 text-sm font-bold ${i===0?"border-blue-600 text-blue-700":"border-transparent text-slate-700 hover:text-blue-700"}`}>{label}</Link>)}</div></nav>
    <div className="mx-auto grid max-w-[1440px] gap-6 px-5 py-7 lg:grid-cols-[minmax(0,1fr)_330px] lg:px-8">
      <main className="min-w-0 space-y-7">
        <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><BookOpen className="text-blue-600"/>Présentation</h2><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_240px]"><div><p className="leading-7 text-slate-600">GuySkull International School est une vitrine de démonstration Écoles237. Elle illustre une école bilingue exigeante, attentive à la réussite académique, au suivi personnalisé et à l’ouverture internationale.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{[[UsersRound,"Enseignement bilingue","Français - Anglais"],[GraduationCap,"Classes à effectif réduit","Suivi personnalisé"],[ShieldCheck,"Encadrement de qualité","Enseignants expérimentés"],[Trophy,"Ouverture internationale","Préparation aux études supérieures"]].map(([Icon,t,d])=><div key={String(t)} className="flex gap-3 rounded-xl border border-slate-100 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-600"><Icon size={20}/></div><div><p className="font-bold">{String(t)}</p><p className="text-sm text-slate-500">{String(d)}</p></div></div>)}</div></div><blockquote className="rounded-2xl bg-gradient-to-br from-blue-50 to-sky-100 p-6 text-lg italic leading-8 text-[#183467]">“Former aujourd’hui les leaders de demain, avec des valeurs fortes et une vision globale.”<footer className="mt-4 text-right font-serif">La Direction</footer></blockquote></div></section>
        <section><h2 className="mb-4 flex items-center gap-3 text-2xl font-black"><GraduationCap className="text-emerald-600"/>Programmes et niveaux</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{levels.map(l=><div key={l.title} className={`rounded-2xl p-5 ${l.tone}`}><p className="font-black">{l.title}</p><p className="mt-3 text-sm leading-6 text-slate-700">{l.detail}</p><p className="text-sm text-slate-600">{l.age}</p></div>)}</div></section>
        <section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-black">Frais de scolarité</h2><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-600">Tarifs de démonstration</span></div><p className="mt-2 text-sm text-slate-500">Ces tarifs servent uniquement à illustrer la présentation et doivent être confirmés par l’établissement.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-100 text-left"><tr>{["Niveau","Frais annuels (FCFA)","1er trimestre","2e trimestre","3e trimestre"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{[["Maternelle","450 000","150 000","150 000","150 000"],["Primaire","550 000","183 000","183 000","184 000"],["Secondaire 1er cycle","650 000","217 000","217 000","216 000"],["Secondaire 2nd cycle","750 000","250 000","250 000","250 000"]].map(r=><tr key={r[0]} className="border-b border-slate-100">{r.map((c,i)=><td key={`${c}-${i}`} className={`px-4 py-3 ${i===1?"font-black":""}`}>{c}</td>)}</tr>)}</tbody></table></div></section>
        <section><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-3 text-2xl font-black"><Camera className="text-blue-600"/>Galerie photos</h2><Link href={buildMiniSiteViewHref(baseHref,"galerie")} className="text-sm font-bold text-blue-600">Voir toutes les photos →</Link></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{gallery.map((img,i)=><div key={img} className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={`/images/guyskull/${img}`} alt={`GuySkull - vue ${i+1}`} fill sizes="(max-width:768px) 50vw, 180px" className="object-cover"/></div>)}</div></section>
        <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><Trophy className="text-emerald-600"/>Résultats et performances</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Taux de réussite BEPC","100%","bg-emerald-50 text-emerald-700"],["Taux de réussite Baccalauréat","98%","bg-blue-50 text-blue-700"],["Mentions au Bac","85%","bg-violet-50 text-violet-700"],["Classement (Douala)","Top 10","bg-orange-50 text-orange-700"]].map(([l,v,c])=><div key={l} className={`rounded-xl p-5 text-center ${c}`}><p className="text-xs font-bold">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></div>)}</div><p className="mt-3 text-xs text-slate-400">Données de démonstration à confirmer par l’établissement.</p></section>
      </main>
      <aside className="space-y-4 lg:sticky lg:top-36 lg:self-start"><div className="rounded-2xl bg-white p-4 shadow-sm"><Link href={data.preinscriptionHref} className="flex h-13 items-center justify-center rounded-xl bg-emerald-600 font-bold text-white"><UsersRound className="mr-2" size={19}/>Inscrire mon enfant</Link>{phone&&<a href={`tel:${phone}`} className="mt-2 flex h-11 items-center justify-center rounded-xl border font-bold"><Phone className="mr-2 text-emerald-600" size={17}/>Contacter l’établissement</a>}{whatsapp&&<a href={`https://wa.me/${whatsapp.replace(/\D/g,"")}`} className="mt-2 flex h-11 items-center justify-center rounded-xl border font-bold"><MessageCircle className="mr-2 text-emerald-600" size={17}/>Écrire sur WhatsApp</a>}</div><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black"><Building2 className="text-emerald-600"/>Informations pratiques</h2><dl className="mt-4 space-y-4 text-sm"><div className="flex gap-3"><MapPin className="text-emerald-600" size={17}/><div><dt className="font-bold">Localisation</dt><dd className="text-slate-500">{location}</dd></div></div>{phone&&<div className="flex gap-3"><Phone className="text-emerald-600" size={17}/><div><dt className="font-bold">Téléphone</dt><dd className="text-slate-500">{phone}</dd></div></div>}{school.email&&<div className="flex gap-3"><Mail className="text-emerald-600" size={17}/><div><dt className="font-bold">Email</dt><dd className="break-all text-blue-600">{school.email}</dd></div></div>}<div className="flex gap-3"><CheckCircle2 className="text-emerald-600" size={17}/><div><dt className="font-bold">Statut</dt><dd className="text-emerald-600">Établissement vérifié</dd></div></div></dl></div><div className="overflow-hidden rounded-2xl bg-white p-4 shadow-sm"><h2 className="mb-3 flex items-center gap-2 text-xl font-black"><MapPin className="text-emerald-600"/>Localisation</h2><div className="relative h-64 overflow-hidden rounded-xl"><Image src="/images/guyskull/guyskull-facade-v1.png" alt="Localisation illustrative GuySkull" fill sizes="300px" className="object-cover opacity-40"/><div className="absolute inset-0 grid place-items-center bg-blue-50/60 text-center"><div><MapPin className="mx-auto text-red-500" size={36}/><p className="mt-2 font-black">{location}</p><p className="text-xs text-slate-500">Aperçu illustratif</p></div></div></div></div></aside>
    </div>
  </div>;
}
