"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { BookOpen, Building2, Camera, CheckCircle2, ChevronLeft, ChevronRight, GraduationCap, Heart, Mail, MapPin, MessageCircle, Phone, ShieldCheck, Trophy, UsersRound } from "lucide-react";
import type { MiniSiteRendererData } from "@/lib/schoolPage/miniSiteData";
import type { MiniSiteViewKey } from "@/lib/schoolPage/miniSiteViews";

const gallery = ["guyskull-facade-v1.png", "guyskull-classroom-v1.png", "guyskull-school-life-concept-v1.png", "guyskull-computer-room-concept-v1.png", "guyskull-play-sport-concept-v1.png", "guyskull-library-concept-v1.png"];
const heroImages = ["guyskull-campus-master-v1.png", "guyskull-facade-v1.png", "guyskull-courtyard-v1.png"];
type GuyskullTab = "accueil" | "apropos" | "programmes" | "frais" | "vie" | "resultats" | "galerie" | "actualites" | "contact";
const levels = [
  { title: "Garderie & Maternelle", detail: "Crèche, Petite, Moyenne et Grande Section", age: "1 – 5 ans", tone: "bg-emerald-50 text-emerald-700" },
  { title: "Primaire", detail: "CI · CP · CE1 · CE2 · CM1 · CM2", age: "6 – 11 ans", tone: "bg-blue-50 text-blue-700" },
];

export function GuyskullShowcase({ data, baseHref, activeView = "accueil" }: { data: MiniSiteRendererData; baseHref: string; activeView?: MiniSiteViewKey }) {
  const [activeHero, setActiveHero] = useState(0);
  const [activeTab, setActiveTab] = useState<GuyskullTab>(activeView === "accueil" ? "accueil" : activeView === "etablissement" ? "apropos" : activeView === "admissions" ? "programmes" : activeView === "vie" ? "vie" : "galerie");
  useEffect(() => {
    const media = window.matchMedia("(prefers-reduced-motion: reduce)");
    if (media.matches) return;
    const timer = window.setInterval(() => setActiveHero((current) => (current + 1) % heroImages.length), 5500);
    return () => window.clearInterval(timer);
  }, []);
  const school = data.establishment;
  const phone = school.phone;
  const whatsapp = school.whatsapp;
  const location = [school.neighborhood, school.city].filter(Boolean).join(", ") || "Douala, Cameroun";
  const nav: [string, GuyskullTab][] = [
    ["Accueil", "accueil"], ["À propos", "apropos"], ["Programmes", "programmes"], ["Frais de scolarité", "frais"], ["Vie scolaire", "vie"], ["Résultats", "resultats"], ["Galerie", "galerie"], ["Actualités", "actualites"], ["Contact", "contact"],
  ] as const;
  return <div className="bg-[#f8fafc] text-[#102750]">
    <section className="relative min-h-[430px] overflow-hidden">
      {heroImages.map((image, index) => <Image key={image} src={`/images/guyskull/${image}`} alt={index === activeHero ? "Campus GuySkull International School" : ""} fill priority={index === 0} sizes="100vw" className={`object-cover object-center transition-opacity duration-700 ${index === activeHero ? "opacity-100" : "opacity-0"}`} />)}
      <div className="absolute inset-0 bg-gradient-to-r from-[#052d64]/80 via-[#07539b]/45 to-transparent" />
      <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-[#052d64]/55 to-transparent" />
      <div className="relative mx-auto flex min-h-[390px] max-w-[1440px] items-end gap-8 px-5 pb-8 pt-24 lg:px-8">
        <div className="relative hidden h-56 w-56 shrink-0 overflow-hidden rounded-[34px] border-4 border-white bg-white p-3 shadow-2xl md:block">
          <Image src="/images/guyskull/guyskull-logo-v1.png" alt="Logo GuySkull International School" fill sizes="224px" className="object-contain p-3" />
        </div>
        <div className="min-w-0 flex-1 text-white"><h1 className="text-4xl font-black tracking-tight md:text-5xl">GuySkull International School</h1><p className="mt-2 text-lg">Discipline • Excellence • Ouverture sur le monde</p>
          <div className="mt-5 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">Établissement privé</span><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">Bilingue (Français - Anglais)</span><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">Garderie</span><span className="rounded-lg bg-white px-3 py-2 text-[#102750]">École primaire</span></div>
          <div className="mt-5 flex flex-wrap items-center gap-4 text-sm font-semibold"><span className="inline-flex items-center gap-2"><MapPin size={17}/>{location}</span><span className="inline-flex items-center gap-2 rounded-lg bg-emerald-100 px-3 py-2 text-emerald-700"><CheckCircle2 size={17}/>Établissement vérifié</span></div>
        </div>
        <div className="absolute right-5 top-5 flex gap-3"><button className="rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#102750] shadow"><Heart size={17} className="mr-2 inline"/>Ajouter aux favoris</button></div>
        <div className="absolute bottom-5 right-5 flex items-center gap-2"><button type="button" aria-label="Photo précédente" onClick={() => setActiveHero((activeHero - 1 + heroImages.length) % heroImages.length)} className="grid h-10 w-10 place-items-center rounded-full bg-white/95 text-[#102750] shadow"><ChevronLeft size={20}/></button><div className="flex gap-1.5 rounded-full bg-black/25 px-3 py-2 backdrop-blur">{heroImages.map((image,index)=><button type="button" aria-label={`Afficher la photo ${index + 1}`} key={image} onClick={()=>setActiveHero(index)} className={`h-2 rounded-full transition-all ${index===activeHero?"w-6 bg-white":"w-2 bg-white/55"}`}/>)}</div><button type="button" aria-label="Photo suivante" onClick={() => setActiveHero((activeHero + 1) % heroImages.length)} className="grid h-10 w-10 place-items-center rounded-full bg-white/95 text-[#102750] shadow"><ChevronRight size={20}/></button></div>
      </div>
    </section>
    <nav aria-label="Sections de l’établissement" className="sticky top-[72px] z-30 overflow-x-auto border-b border-slate-200 bg-white shadow-sm"><div className="mx-auto flex min-w-max max-w-[1440px] px-4">{nav.map(([label,key], i)=><button type="button" key={`${label}-${i}`} onClick={()=>setActiveTab(key)} aria-current={activeTab === key ? "page" : undefined} className={`flex h-14 items-center gap-2 border-b-2 px-4 text-sm font-bold ${activeTab===key?"border-blue-600 text-blue-700":"border-transparent text-slate-700 hover:text-blue-700"}`}>{label}</button>)}</div></nav>
    <div className="mx-auto grid max-w-[1440px] gap-6 px-5 py-7 lg:grid-cols-[minmax(0,1fr)_330px] lg:px-8">
      <main className="min-w-0 space-y-7">{activeTab === "accueil" ? <>
        <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><BookOpen className="text-blue-600"/>Présentation</h2><div className="mt-5 grid gap-6 lg:grid-cols-[1fr_240px]"><div><p className="leading-7 text-slate-600">GuySkull International School est une vitrine de démonstration Écoles237. Elle illustre une école bilingue exigeante, attentive à la réussite académique, au suivi personnalisé et à l’ouverture internationale.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{[[UsersRound,"Enseignement bilingue","Français - Anglais"],[GraduationCap,"Classes à effectif réduit","Suivi personnalisé"],[ShieldCheck,"Encadrement de qualité","Enseignants expérimentés"],[Trophy,"Ouverture internationale","Préparation aux études supérieures"]].map(([Icon,t,d])=><div key={String(t)} className="flex gap-3 rounded-xl border border-slate-100 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-600"><Icon size={20}/></div><div><p className="font-bold">{String(t)}</p><p className="text-sm text-slate-500">{String(d)}</p></div></div>)}</div></div><blockquote className="rounded-2xl bg-gradient-to-br from-blue-50 to-sky-100 p-6 text-lg italic leading-8 text-[#183467]">“Former aujourd’hui les leaders de demain, avec des valeurs fortes et une vision globale.”<footer className="mt-4 text-right font-serif">La Direction</footer></blockquote></div></section>
        <section><h2 className="mb-4 flex items-center gap-3 text-2xl font-black"><GraduationCap className="text-emerald-600"/>Programmes et niveaux</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{levels.map(l=><div key={l.title} className={`rounded-2xl p-5 ${l.tone}`}><p className="font-black">{l.title}</p><p className="mt-3 text-sm leading-6 text-slate-700">{l.detail}</p><p className="text-sm text-slate-600">{l.age}</p></div>)}</div></section>
        <section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-black">Frais de scolarité</h2><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-600">Tarifs de démonstration</span></div><p className="mt-2 text-sm text-slate-500">Ces tarifs servent uniquement à illustrer la présentation et doivent être confirmés par l’établissement.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-100 text-left"><tr>{["Niveau","Frais annuels (FCFA)","1er trimestre","2e trimestre","3e trimestre"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{[["Garderie & Maternelle","450 000","150 000","150 000","150 000"],["École primaire","550 000","183 000","183 000","184 000"]].map(r=><tr key={r[0]} className="border-b border-slate-100">{r.map((c,i)=><td key={`${c}-${i}`} className={`px-4 py-3 ${i===1?"font-black":""}`}>{c}</td>)}</tr>)}</tbody></table></div></section>
        <section><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-3 text-2xl font-black"><Camera className="text-blue-600"/>Galerie photos</h2><button type="button" onClick={()=>setActiveTab("galerie")} className="text-sm font-bold text-blue-600">Voir toutes les photos →</button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{gallery.map((img,i)=><div key={img} className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={`/images/guyskull/${img}`} alt={`GuySkull - vue ${i+1}`} fill sizes="(max-width:768px) 50vw, 180px" className="object-cover"/></div>)}</div></section>
        <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><Trophy className="text-emerald-600"/>Résultats et performances</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["Passage en classe supérieure","98%","bg-emerald-50 text-emerald-700"],["Satisfaction des familles","95%","bg-blue-50 text-blue-700"]].map(([l,v,c])=><div key={l} className={`rounded-xl p-5 text-center ${c}`}><p className="text-xs font-bold">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></div>)}</div><p className="mt-3 text-xs text-slate-400">Données de démonstration à confirmer par l’établissement.</p></section>
      </> : <GuyskullTabContent activeTab={activeTab} data={data} />}</main>
      <aside className="space-y-4 lg:sticky lg:top-36 lg:self-start"><div className="rounded-2xl bg-white p-4 shadow-sm"><Link href={data.preinscriptionHref} className="flex h-13 items-center justify-center rounded-xl bg-emerald-600 font-bold text-white"><UsersRound className="mr-2" size={19}/>Inscrire mon enfant</Link>{phone&&<a href={`tel:${phone}`} className="mt-2 flex h-11 items-center justify-center rounded-xl border font-bold"><Phone className="mr-2 text-emerald-600" size={17}/>Contacter l’établissement</a>}{whatsapp&&<a href={`https://wa.me/${whatsapp.replace(/\D/g,"")}`} className="mt-2 flex h-11 items-center justify-center rounded-xl border font-bold"><MessageCircle className="mr-2 text-emerald-600" size={17}/>Écrire sur WhatsApp</a>}</div><div className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-black"><Building2 className="text-emerald-600"/>Informations pratiques</h2><dl className="mt-4 space-y-4 text-sm"><div className="flex gap-3"><MapPin className="text-emerald-600" size={17}/><div><dt className="font-bold">Localisation</dt><dd className="text-slate-500">{location}</dd></div></div>{phone&&<div className="flex gap-3"><Phone className="text-emerald-600" size={17}/><div><dt className="font-bold">Téléphone</dt><dd className="text-slate-500">{phone}</dd></div></div>}{school.email&&<div className="flex gap-3"><Mail className="text-emerald-600" size={17}/><div><dt className="font-bold">Email</dt><dd className="break-all text-blue-600">{school.email}</dd></div></div>}<div className="flex gap-3"><CheckCircle2 className="text-emerald-600" size={17}/><div><dt className="font-bold">Statut</dt><dd className="text-emerald-600">Établissement vérifié</dd></div></div></dl></div><div className="overflow-hidden rounded-2xl bg-white p-4 shadow-sm"><h2 className="mb-3 flex items-center gap-2 text-xl font-black"><MapPin className="text-emerald-600"/>Localisation</h2><div className="relative h-64 overflow-hidden rounded-xl"><Image src="/images/guyskull/guyskull-facade-v1.png" alt="Localisation illustrative GuySkull" fill sizes="300px" className="object-cover opacity-40"/><div className="absolute inset-0 grid place-items-center bg-blue-50/60 text-center"><div><MapPin className="mx-auto text-red-500" size={36}/><p className="mt-2 font-black">{location}</p><p className="text-xs text-slate-500">Aperçu illustratif</p></div></div></div></div></aside>
    </div>
  </div>;
}

function GuyskullTabContent({ activeTab, data }: { activeTab: Exclude<GuyskullTab, "accueil">; data: MiniSiteRendererData }) {
  if (activeTab === "apropos") return <>
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><BookOpen className="text-blue-600"/>À propos de GuySkull</h2><p className="mt-5 leading-7 text-slate-600">GuySkull International School accompagne les enfants de la garderie jusqu’à la fin du primaire dans un environnement bilingue, sécurisé et stimulant.</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["Mission","Donner à chaque enfant des bases solides et le goût d’apprendre."],["Vision","Former des élèves curieux, autonomes et ouverts sur le monde."],["Valeurs","Discipline, excellence, bienveillance et responsabilité."]].map(([title,text])=><article key={title} className="rounded-xl bg-blue-50 p-5"><h3 className="font-black text-blue-800">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></section>
    <section><h2 className="mb-4 text-2xl font-black">Notre environnement</h2><div className="grid gap-3 sm:grid-cols-2">{["guyskull-courtyard-v1.png","guyskull-classroom-v1.png"].map((image,index)=><div key={image} className="relative aspect-[16/9] overflow-hidden rounded-2xl"><Image src={`/images/guyskull/${image}`} alt={index===0?"Cour GuySkull":"Salle de classe GuySkull"} fill sizes="50vw" className="object-cover"/></div>)}</div></section>
  </>;

  if (activeTab === "programmes") return <>
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><GraduationCap className="text-emerald-600"/>Formations et admissions</h2><p className="mt-3 text-slate-600">Deux parcours simples, adaptés au rythme et à l’âge de chaque enfant.</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{levels.map(level=><article key={level.title} className={`rounded-2xl p-6 ${level.tone}`}><h3 className="text-lg font-black">{level.title}</h3><p className="mt-3 text-sm leading-6 text-slate-700">{level.detail}</p><p className="text-sm text-slate-600">{level.age}</p></article>)}</div></section>
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Comment inscrire votre enfant ?</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{["Choisir le niveau","Préparer le dossier","Contacter l’établissement"].map((step,index)=><div key={step} className="rounded-xl border border-slate-100 p-5"><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-600 font-black text-white">{index+1}</span><p className="mt-3 font-bold">{step}</p></div>)}</div><Link href="/preinscription" className="mt-6 inline-flex rounded-xl bg-emerald-600 px-6 py-3 font-bold text-white">Commencer la préinscription</Link></section>
  </>;

  if (activeTab === "frais") return <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Frais de scolarité</h2><span className="mt-3 inline-flex rounded-full bg-red-100 px-3 py-1 text-xs font-bold text-red-600">Tarifs de démonstration</span><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-sm"><thead className="bg-slate-100 text-left"><tr>{["Niveau","Frais annuels","1er trimestre","2e trimestre","3e trimestre"].map(label=><th key={label} className="p-4">{label}</th>)}</tr></thead><tbody>{[["Garderie & Maternelle","450 000","150 000","150 000","150 000"],["École primaire","550 000","183 000","183 000","184 000"]].map(row=><tr key={row[0]} className="border-b">{row.map((cell,index)=><td key={`${cell}-${index}`} className={`p-4 ${index===1?"font-black":""}`}>{cell}</td>)}</tr>)}</tbody></table></div></section>;

  if (activeTab === "vie") return <>
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><Trophy className="text-emerald-600"/>Vie scolaire et résultats</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-emerald-50 p-6 text-center"><p className="text-sm font-bold text-emerald-700">Passage en classe supérieure</p><p className="mt-2 text-4xl font-black text-emerald-700">98%</p></div><div className="rounded-xl bg-blue-50 p-6 text-center"><p className="text-sm font-bold text-blue-700">Satisfaction des familles</p><p className="mt-2 text-4xl font-black text-blue-700">95%</p></div></div><p className="mt-3 text-xs text-slate-400">Données de démonstration à confirmer par l’établissement.</p></section>
    <section><h2 className="mb-4 text-2xl font-black">Une école vivante</h2><div className="grid gap-3 sm:grid-cols-3">{["guyskull-school-life-concept-v1.png","guyskull-pedagogical-activity-v1.png","guyskull-play-sport-concept-v1.png"].map((image,index)=><div key={image} className="relative aspect-[4/3] overflow-hidden rounded-2xl"><Image src={`/images/guyskull/${image}`} alt={`Vie scolaire GuySkull ${index+1}`} fill sizes="33vw" className="object-cover"/></div>)}</div></section>
  </>;

  if (activeTab === "resultats") return <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="flex items-center gap-3 text-2xl font-black"><Trophy className="text-emerald-600"/>Résultats et performances</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-emerald-50 p-7 text-center"><p className="font-bold text-emerald-700">Passage en classe supérieure</p><p className="mt-2 text-4xl font-black text-emerald-700">98%</p></div><div className="rounded-xl bg-blue-50 p-7 text-center"><p className="font-bold text-blue-700">Satisfaction des familles</p><p className="mt-2 text-4xl font-black text-blue-700">95%</p></div></div><p className="mt-4 text-xs text-slate-400">Données de démonstration à confirmer par l’établissement.</p></section>;

  if (activeTab === "actualites") return <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Actualités</h2><div className="mt-5 space-y-3">{["Journée portes ouvertes","Atelier parents-enfants","Journée créative et sportive"].map((title,index)=><article key={title} className="rounded-xl border border-slate-100 p-5"><p className="text-xs font-bold text-blue-600">Actualité {index+1}</p><h3 className="mt-1 font-black">{title}</h3><p className="mt-2 text-sm text-slate-500">Information de démonstration à confirmer par l’établissement.</p></article>)}</div></section>;

  if (activeTab === "contact") return <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-2xl font-black">Contact</h2><p className="mt-3 text-slate-600">Une question sur la garderie, le primaire ou les inscriptions ? Contactez directement l’établissement.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{data.establishment.phone&&<a href={`tel:${data.establishment.phone}`} className="flex items-center gap-3 rounded-xl border p-5 font-bold"><Phone className="text-emerald-600"/>{data.establishment.phone}</a>}{data.establishment.email&&<a href={`mailto:${data.establishment.email}`} className="flex items-center gap-3 rounded-xl border p-5 font-bold"><Mail className="text-emerald-600"/>{data.establishment.email}</a>}</div></section>;

  return <>
    <section><div className="mb-4 flex items-end justify-between"><div><h2 className="flex items-center gap-3 text-2xl font-black"><Camera className="text-blue-600"/>Galerie et informations</h2><p className="mt-2 text-slate-500">Découvrez les espaces et la vie quotidienne de l’établissement.</p></div></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{gallery.map((image,index)=><div key={image} className="relative aspect-[4/3] overflow-hidden rounded-2xl"><Image src={`/images/guyskull/${image}`} alt={`Galerie GuySkull ${index+1}`} fill sizes="33vw" className="object-cover transition-transform hover:scale-105"/></div>)}</div></section>
    <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Informations utiles</h2><p className="mt-3 text-slate-600">Les coordonnées, boutons d’appel et informations pratiques restent disponibles dans la colonne de droite.</p></section>
  </>;
}
