import Image from "next/image";
import { redirect } from "next/navigation";
import { AlertTriangle, Clock3, ImageIcon, TimerReset } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { requireActiveEstablishment } from "@/lib/supabase/activeEstablishment";
import { SchoolAdminPageHeader } from "@/components/school-admin/ui/PageHeader";
import { SchoolAdminStatCard } from "@/components/school-admin/ui/StatCard";
import { SchoolAdminFilterBar } from "@/components/school-admin/ui/FilterBar";
import { SchoolAdminStatusBadge } from "@/components/school-admin/ui/Badge";
import { SchoolAdminResponsiveTable } from "@/components/school-admin/ui/ResponsiveTable";
import { SchoolAdminButton } from "@/components/school-admin/ui/Button";
import { SchoolAdminFormField, SchoolAdminInput, SchoolAdminSelect } from "@/components/school-admin/ui/FormControls";
import { SchoolAdminAlert, SchoolAdminEmptyState } from "@/components/school-admin/ui/Feedback";

export default async function HistoriquePage({ searchParams }: { searchParams: Promise<{ enseignant?: string; debut?: string; fin?: string; school?: string }> }) {
  const supabase = await createClient(); const params = await searchParams;
  const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/auth/connexion");
  const etablissement = await requireActiveEstablishment(supabase, user.id, params.school, "/pro/pointage/historique");
  const etablissementId = etablissement.id;
  const today = new Date(); const defaultFin = today.toISOString().slice(0, 10); const defaultDebut = new Date(today.getFullYear(), today.getMonth(), 1).toISOString().slice(0, 10);
  const debut = params.debut ?? defaultDebut; const fin = params.fin ?? defaultFin;
  const { data: enseignants } = await supabase.from("enseignants").select("id, nom, prenom, taux_horaire").eq("etablissement_id", etablissementId).order("nom");
  if (!enseignants?.length) return <div className="mx-auto max-w-6xl"><SchoolAdminPageHeader eyebrow="Présences" title="Historique des présences" description="Consultez les pointages par enseignant et par période." /><SchoolAdminEmptyState title="Aucun enseignant enregistré" description="L’historique sera disponible lorsqu’un enseignant existera dans cet établissement." /></div>;
  const enseignantSelectionne = enseignants.find((enseignant) => enseignant.id === params.enseignant) ?? enseignants[0];
  const { data: pointages } = await supabase.from("pointages").select("id, type, horodatage, photo_path").eq("etablissement_id", etablissementId).eq("enseignant_id", enseignantSelectionne.id).gte("horodatage", `${debut}T00:00:00`).lte("horodatage", `${fin}T23:59:59`).order("horodatage", { ascending: true });
  const { data: totalHeures } = await supabase.rpc("calculer_heures_enseignant", { p_enseignant_id: enseignantSelectionne.id, p_date_debut: debut, p_date_fin: fin, p_etablissement_id: etablissementId });
  const signedUrls: (string | null)[] = await Promise.all((pointages ?? []).map((pointage) => supabase.storage.from("pointages-photos").createSignedUrl(pointage.photo_path, 3600).then((result) => result.data?.signedUrl ?? null).catch(() => null)));
  const byDate = new Map<string, { arrivees: string[]; departs: string[] }>();
  for (const pointage of pointages ?? []) { const date = pointage.horodatage.slice(0, 10); const entry = byDate.get(date) ?? { arrivees: [], departs: [] }; if (pointage.type === "arrivee") entry.arrivees.push(pointage.horodatage); else entry.departs.push(pointage.horodatage); byDate.set(date, entry); }
  const incompleteDays = new Set<string>();
  for (const [date, { arrivees, departs }] of Array.from(byDate.entries())) for (const arrivee of arrivees) if (!departs.some((depart) => depart > arrivee)) { incompleteDays.add(date); break; }
  const heures = Number(totalHeures ?? 0); const salaireEstime = enseignantSelectionne.taux_horaire && heures > 0 ? Math.round(heures * enseignantSelectionne.taux_horaire) : null;
  const rows = pointages ?? [];
  const formatHours = heures.toFixed(2).replace(".", "h").replace(/h(\d+)$/, (_, minutes) => `h${minutes.padStart(2, "0")}`);

  return <div className="mx-auto max-w-6xl">
    <SchoolAdminPageHeader eyebrow="Présences" title="Historique des présences" description="Consultez les pointages et les photos privées générées pour la période sélectionnée." />
    <form method="GET" action="/pro/pointage/historique"><input type="hidden" name="school" value={etablissementId} /><SchoolAdminFilterBar className="mb-6" actions={<SchoolAdminButton type="submit">Appliquer</SchoolAdminButton>}><SchoolAdminFormField id="attendance-teacher" label="Enseignant"><SchoolAdminSelect name="enseignant" defaultValue={enseignantSelectionne.id}>{enseignants.map((enseignant) => <option key={enseignant.id} value={enseignant.id}>{enseignant.prenom} {enseignant.nom}</option>)}</SchoolAdminSelect></SchoolAdminFormField><SchoolAdminFormField id="attendance-start" label="Du"><SchoolAdminInput type="date" name="debut" defaultValue={debut} /></SchoolAdminFormField><SchoolAdminFormField id="attendance-end" label="Au"><SchoolAdminInput type="date" name="fin" defaultValue={fin} /></SchoolAdminFormField></SchoolAdminFilterBar></form>
    <div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><SchoolAdminStatCard label="Total heures" value={formatHours} icon={<Clock3 size={19} />} /><SchoolAdminStatCard label="Pointages" value={rows.length} icon={<TimerReset size={19} />} tone="neutral" /><SchoolAdminStatCard label="Anomalies" value={incompleteDays.size} icon={<AlertTriangle size={19} />} tone={incompleteDays.size ? "warning" : "neutral"} detail="Arrivée sans départ correspondant" />{salaireEstime !== null && <SchoolAdminStatCard label="Salaire estimé" value={`${salaireEstime.toLocaleString("fr-FR")} FCFA`} icon={<Clock3 size={19} />} tone="neutral" />}</div>
    {incompleteDays.size > 0 && <div className="mb-5"><SchoolAdminAlert tone="warning" title={`${incompleteDays.size} jour(s) incomplet(s)`}>{Array.from(incompleteDays).sort().map((date) => new Date(date).toLocaleDateString("fr-FR", { day: "2-digit", month: "short" })).join(", ")}. Ces heures ne sont pas comptabilisées dans le total.</SchoolAdminAlert></div>}
    {!rows.length ? <SchoolAdminEmptyState title="Aucun pointage sur cette période" description="Modifiez l’enseignant ou les dates pour consulter un autre intervalle." /> : <><SchoolAdminResponsiveTable label="Historique des pointages" className="hidden md:block"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[var(--school-admin-surface-muted)] text-xs uppercase tracking-wide text-[var(--school-admin-text-muted)]"><tr><th scope="col" className="px-5 py-3">Date</th><th scope="col" className="px-5 py-3">Heure</th><th scope="col" className="px-5 py-3">Mouvement</th><th scope="col" className="px-5 py-3">État</th><th scope="col" className="px-5 py-3">Photo privée</th></tr></thead><tbody className="divide-y divide-[var(--school-admin-border)]">{rows.map((pointage, index) => <AttendanceRow key={pointage.id} pointage={pointage} signedUrl={signedUrls[index]} incompleteDays={incompleteDays} />)}</tbody></table></SchoolAdminResponsiveTable><div className="space-y-3 md:hidden" aria-label="Historique des pointages">{rows.map((pointage, index) => <AttendanceCard key={pointage.id} pointage={pointage} signedUrl={signedUrls[index]} incompleteDays={incompleteDays} />)}</div></>}
  </div>;
}

function AttendancePhoto({ signedUrl, label }: { signedUrl: string | null; label: string }) {
  return signedUrl ? <a href={signedUrl} target="_blank" rel="noopener noreferrer" aria-label={`Ouvrir la photo privée du pointage ${label}`} className="inline-flex rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--school-admin-focus)]"><Image src={signedUrl} alt="Photo privée du pointage" width={56} height={44} unoptimized className="h-11 w-14 rounded-lg border border-[var(--school-admin-border)] object-cover" /></a> : <span className="inline-flex items-center gap-1 text-xs text-[var(--school-admin-text-soft)]"><ImageIcon size={14} aria-hidden="true" />Indisponible</span>;
}
function statusFor(pointage: any, incompleteDays: Set<string>) { return incompleteDays.has(pointage.horodatage.slice(0, 10)) && pointage.type === "arrivee"; }
function AttendanceRow({ pointage, signedUrl, incompleteDays }: { pointage: any; signedUrl: string | null; incompleteDays: Set<string> }) { const date = new Date(pointage.horodatage); const incomplete = statusFor(pointage, incompleteDays); const label = date.toLocaleString("fr-FR"); return <tr className={incomplete ? "bg-[var(--school-admin-warning-soft)]" : "hover:bg-[var(--school-admin-surface-muted)]"}><th scope="row" className="px-5 py-4 font-semibold">{date.toLocaleDateString("fr-FR", { weekday: "short", day: "2-digit", month: "short" })}</th><td className="px-5 py-4">{date.toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" })}</td><td className="px-5 py-4"><SchoolAdminStatusBadge tone={pointage.type === "arrivee" ? "success" : "info"} label={pointage.type === "arrivee" ? "Arrivée" : "Départ"} /></td><td className="px-5 py-4"><SchoolAdminStatusBadge tone={incomplete ? "warning" : "neutral"} label={incomplete ? "Anomalie : départ manquant" : "Enregistré"} /></td><td className="px-5 py-4"><AttendancePhoto signedUrl={signedUrl} label={label} /></td></tr>; }
function AttendanceCard({ pointage, signedUrl, incompleteDays }: { pointage: any; signedUrl: string | null; incompleteDays: Set<string> }) { const date = new Date(pointage.horodatage); const incomplete = statusFor(pointage, incompleteDays); return <article className="rounded-xl border border-[var(--school-admin-border)] bg-[var(--school-admin-surface)] p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold">{date.toLocaleDateString("fr-FR", { weekday: "long", day: "2-digit", month: "long" })}</h2><p className="mt-1 text-sm text-[var(--school-admin-text-muted)]">{date.toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" })}</p></div><SchoolAdminStatusBadge tone={pointage.type === "arrivee" ? "success" : "info"} label={pointage.type === "arrivee" ? "Arrivée" : "Départ"} /></div><div className="mt-4 flex items-center justify-between border-t border-[var(--school-admin-border)] pt-3"><SchoolAdminStatusBadge tone={incomplete ? "warning" : "neutral"} label={incomplete ? "Anomalie : départ manquant" : "Enregistré"} /><AttendancePhoto signedUrl={signedUrl} label={date.toLocaleString("fr-FR")} /></div></article>; }
