"use client";
import { useCallback, useEffect, useState } from "react";
import { Bell, Plus, Trash2 } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useSchool } from "@/lib/useSchool";
import { SchoolAdminPageHeader } from "@/components/school-admin/ui/PageHeader";
import { SchoolAdminStatusBadge } from "@/components/school-admin/ui/Badge";
import { SchoolAdminButton } from "@/components/school-admin/ui/Button";
import { SchoolAdminDialog } from "@/components/school-admin/ui/Overlay";
import { SchoolAdminFormField, SchoolAdminInput, SchoolAdminTextarea } from "@/components/school-admin/ui/FormControls";
import { SchoolAdminAlert, SchoolAdminEmptyState, SchoolAdminLoadingState } from "@/components/school-admin/ui/Feedback";

export default function AnnoncesPage() {
  const { school, loading: schoolLoading } = useSchool(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [deleteTarget, setDeleteTarget] = useState<any | null>(null); const [deleting, setDeleting] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [form, setForm] = useState({ title: "", content: "", is_important: false });
  const load = useCallback(async (schoolId: string) => { setLoading(true); const { data, error: loadError } = await supabase.from("school_announcements").select("*").eq("establishment_id", schoolId).order("created_at", { ascending: false }); if (loadError) setError(loadError.message); if (data) setItems(data); setLoading(false); }, []);
  useEffect(() => { if (school) load(school.id); }, [school, load]);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!school || saving) return; setSaving(true); setError(""); const { error: createError } = await supabase.from("school_announcements").insert({ establishment_id: school.id, title: form.title, content: form.content, is_important: form.is_important }); setSaving(false); if (createError) { setError(createError.message); return; } setForm({ title: "", content: "", is_important: false }); setShowForm(false); setSuccess("Annonce publiée."); load(school.id); }
  async function remove() { if (!school || !deleteTarget || deleting) return; setDeleting(true); setError(""); const { error: deleteError } = await supabase.from("school_announcements").delete().eq("id", deleteTarget.id); setDeleting(false); if (deleteError) { setError(deleteError.message); return; } setDeleteTarget(null); setSuccess("Annonce supprimée."); load(school.id); }
  if (schoolLoading) return <SchoolAdminLoadingState label="Chargement des annonces" />; if (!school) return <SchoolAdminEmptyState title="Aucun établissement actif" description="Sélectionnez un établissement." />;
  return <div className="mx-auto max-w-5xl"><SchoolAdminPageHeader eyebrow="Communications" title="Annonces publiques" description="Publiez les annonces affichées par les canaux publics existants de l’établissement." actions={<SchoolAdminButton onClick={() => setShowForm(true)} leadingIcon={<Plus size={16} aria-hidden="true" />}>Nouvelle annonce</SchoolAdminButton>} />{error && <div className="mb-5"><SchoolAdminAlert tone="danger">{error}</SchoolAdminAlert></div>}{success && <div className="mb-5"><SchoolAdminAlert tone="success">{success}</SchoolAdminAlert></div>}{loading ? <SchoolAdminLoadingState label="Chargement des annonces" /> : !items.length ? <SchoolAdminEmptyState title="Aucune annonce publiée" description="Les annonces créées apparaîtront ici." icon={<Bell size={24} />} /> : <div className="grid gap-4 md:grid-cols-2">{items.map((item) => <article key={item.id} className="rounded-xl border border-[var(--school-admin-border)] bg-[var(--school-admin-surface)] p-5"><div className="flex items-start justify-between gap-3"><div>{item.is_important && <SchoolAdminStatusBadge tone="danger" label="Important" />}<time className="mt-2 block text-xs text-[var(--school-admin-text-muted)]">{item.created_at ? new Date(item.created_at).toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" }) : "Date indisponible"}</time><h2 className="mt-2 font-bold">{item.title || "Sans titre"}</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[var(--school-admin-text-muted)]">{item.content || "Contenu indisponible"}</p></div><button type="button" onClick={() => setDeleteTarget(item)} aria-label={`Supprimer l’annonce ${item.title}`} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-[var(--school-admin-text-soft)] hover:text-[var(--school-admin-danger)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--school-admin-focus)]"><Trash2 size={16} aria-hidden="true" /></button></div></article>)}</div>}
  <SchoolAdminDialog open={showForm} onClose={() => setShowForm(false)} title="Nouvelle annonce" description="Aucune programmation ou cible supplémentaire ne sera créée."><form onSubmit={create} className="space-y-5"><SchoolAdminFormField id="announcement-title" label="Titre" required><SchoolAdminInput value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></SchoolAdminFormField><SchoolAdminFormField id="announcement-content" label="Contenu" required><SchoolAdminTextarea value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} rows={5} /></SchoolAdminFormField><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={form.is_important} onChange={(event) => setForm({ ...form, is_important: event.target.checked })} className="h-5 w-5" />Marquer comme important</label><div className="flex justify-end gap-2"><SchoolAdminButton variant="ghost" onClick={() => setShowForm(false)}>Annuler</SchoolAdminButton><SchoolAdminButton type="submit" loading={saving}>Publier</SchoolAdminButton></div></form></SchoolAdminDialog>
  <SchoolAdminDialog open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} title="Supprimer cette annonce ?" description="Cette action utilise la suppression existante."><p className="text-sm">{deleteTarget?.title}</p><div className="mt-5 flex justify-end gap-2"><SchoolAdminButton variant="ghost" onClick={() => setDeleteTarget(null)}>Annuler</SchoolAdminButton><SchoolAdminButton variant="danger" loading={deleting} onClick={remove}>Supprimer</SchoolAdminButton></div></SchoolAdminDialog></div>;
}
