"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Download, FileText, Plus, Trash2, Upload } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { useSchool } from "@/lib/useSchool";
import { SchoolAdminPageHeader } from "@/components/school-admin/ui/PageHeader";
import { SchoolAdminButton } from "@/components/school-admin/ui/Button";
import { SchoolAdminDialog } from "@/components/school-admin/ui/Overlay";
import { SchoolAdminFormField, SchoolAdminInput, SchoolAdminSelect } from "@/components/school-admin/ui/FormControls";
import { SchoolAdminStatusBadge } from "@/components/school-admin/ui/Badge";
import { SchoolAdminAlert, SchoolAdminEmptyState, SchoolAdminLoadingState } from "@/components/school-admin/ui/Feedback";

const BUCKET = "school-documents"; const MAX_MB = 10;
const DOC_TYPES = [{ value: "fiche", label: "Fiche de renseignements" }, { value: "inscription", label: "Fiche d’inscription" }, { value: "fournitures", label: "Liste des fournitures" }, { value: "reglement", label: "Règlement intérieur" }, { value: "calendrier", label: "Calendrier scolaire" }, { value: "autre", label: "Autre document" }];
export default function DocumentsPage() {
  const { school, loading: schoolLoading } = useSchool(); const [docs, setDocs] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [name, setName] = useState(""); const [type, setType] = useState("fiche"); const [file, setFile] = useState<File | null>(null); const [uploading, setUploading] = useState(false); const [deleteTarget, setDeleteTarget] = useState<any | null>(null); const [deleting, setDeleting] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const inputRef = useRef<HTMLInputElement>(null);
  const load = useCallback(async () => { if (!school) return; setLoading(true); const { data, error: loadError } = await supabase.from("school_documents").select("*").eq("establishment_id", school.id).order("created_at", { ascending: false }); if (loadError) setError(loadError.message); if (data) setDocs(data); setLoading(false); }, [school]);
  useEffect(() => { load(); }, [load]);
  function handleFileChange(event: React.ChangeEvent<HTMLInputElement>) { const picked = event.target.files?.[0]; if (!picked) return; if (picked.size > MAX_MB * 1024 * 1024) { setError(`Fichier trop volumineux (max ${MAX_MB} Mo).`); return; } setError(""); setFile(picked); if (!name) setName(picked.name.replace(/\.[^/.]+$/, "")); }
  async function upload(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!file || !school || uploading) return; setUploading(true); setError(""); const ext = file.name.split(".").pop(); const path = `${school.id}/${Date.now()}.${ext}`; const { error: storageError } = await supabase.storage.from(BUCKET).upload(path, file, { upsert: false }); if (storageError) { setError(storageError.message); setUploading(false); return; } const { data: { publicUrl } } = supabase.storage.from(BUCKET).getPublicUrl(path); const { error: dbError } = await supabase.from("school_documents").insert({ establishment_id: school.id, name: name.trim() || file.name, type, url: publicUrl, storage_path: path }); setUploading(false); if (dbError) { setError(dbError.message); return; } cancelForm(); setSuccess("Document publié."); load(); }
  async function deleteDoc() { if (!deleteTarget || deleting) return; setDeleting(true); setError(""); const { error: storageError } = await supabase.storage.from(BUCKET).remove([deleteTarget.storage_path]); if (storageError) { setError(storageError.message); setDeleting(false); return; } const { error: dbError } = await supabase.from("school_documents").delete().eq("id", deleteTarget.id); setDeleting(false); if (dbError) { setError(dbError.message); return; } setDeleteTarget(null); setSuccess("Document supprimé."); load(); }
  function cancelForm() { setShowForm(false); setFile(null); setName(""); setType("fiche"); setError(""); if (inputRef.current) inputRef.current.value = ""; }
  if (schoolLoading) return <SchoolAdminLoadingState label="Chargement des documents" />; if (!school) return <SchoolAdminEmptyState title="Aucun établissement actif" description="Sélectionnez un établissement." />;
  return <div className="mx-auto max-w-5xl"><SchoolAdminPageHeader eyebrow="Documents et CMS" title="Documents publics" description="Gérez les documents selon leur visibilité et leur stockage actuels." actions={<SchoolAdminButton onClick={() => setShowForm(true)} leadingIcon={<Plus size={16} aria-hidden="true" />}>Ajouter un document</SchoolAdminButton>} />{error && <div className="mb-5"><SchoolAdminAlert tone="danger">{error}</SchoolAdminAlert></div>}{success && <div className="mb-5"><SchoolAdminAlert tone="success">{success}</SchoolAdminAlert></div>}{loading ? <SchoolAdminLoadingState label="Chargement des documents" /> : !docs.length ? <SchoolAdminEmptyState title="Aucun document publié" description="Les documents ajoutés apparaîtront sur la fiche publique selon le comportement actuel." icon={<FileText size={24} />} /> : <div className="grid gap-3 sm:grid-cols-2">{docs.map((doc) => <article key={doc.id} className="rounded-xl border border-[var(--school-admin-border)] bg-[var(--school-admin-surface)] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><SchoolAdminStatusBadge label={DOC_TYPES.find((item) => item.value === doc.type)?.label || doc.type || "Document"} /><h2 className="mt-3 truncate font-bold">{doc.name}</h2>{doc.created_at && <time className="mt-1 block text-xs text-[var(--school-admin-text-muted)]">{new Date(doc.created_at).toLocaleDateString("fr-FR")}</time>}</div><div className="flex"><a href={doc.url} target="_blank" rel="noopener noreferrer" aria-label={`Ouvrir ${doc.name}`} className="flex h-10 w-10 items-center justify-center rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--school-admin-focus)]"><Download size={16} aria-hidden="true" /></a><button type="button" onClick={() => setDeleteTarget(doc)} aria-label={`Supprimer ${doc.name}`} className="flex h-10 w-10 items-center justify-center rounded-lg text-[var(--school-admin-danger)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--school-admin-focus)]"><Trash2 size={16} aria-hidden="true" /></button></div></div></article>)}</div>}
  <SchoolAdminDialog open={showForm} onClose={cancelForm} title="Ajouter un document" description={`Taille maximale : ${MAX_MB} Mo. Les règles Storage et la visibilité actuelles restent inchangées.`}><form onSubmit={upload} className="space-y-5"><SchoolAdminFormField id="document-type" label="Type"><SchoolAdminSelect value={type} onChange={(event) => setType(event.target.value)}>{DOC_TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</SchoolAdminSelect></SchoolAdminFormField><SchoolAdminFormField id="document-name" label="Nom"><SchoolAdminInput value={name} onChange={(event) => setName(event.target.value)} /></SchoolAdminFormField><SchoolAdminFormField id="document-file" label="Fichier" required><SchoolAdminInput ref={inputRef} type="file" onChange={handleFileChange} /></SchoolAdminFormField>{uploading && <SchoolAdminAlert tone="info">Envoi du document en cours…</SchoolAdminAlert>}<div className="flex justify-end gap-2"><SchoolAdminButton variant="ghost" onClick={cancelForm} disabled={uploading}>Annuler</SchoolAdminButton><SchoolAdminButton type="submit" loading={uploading} disabled={!file} leadingIcon={<Upload size={16} aria-hidden="true" />}>Publier le document</SchoolAdminButton></div></form></SchoolAdminDialog>
  <SchoolAdminDialog open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} title="Supprimer ce document ?" description="Le fichier et son enregistrement seront supprimés selon le flux existant."><p className="text-sm">{deleteTarget?.name}</p><div className="mt-5 flex justify-end gap-2"><SchoolAdminButton variant="ghost" onClick={() => setDeleteTarget(null)}>Annuler</SchoolAdminButton><SchoolAdminButton variant="danger" loading={deleting} onClick={deleteDoc}>Supprimer</SchoolAdminButton></div></SchoolAdminDialog></div>;
}
